name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend
      - name: Build frontend
        run: npm run build
        working-directory: ./frontend
      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist

  build_backend:
    needs: build_frontend
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            package: nodenexus-server
          - os: ubuntu-22.04-arm
            target: aarch64-unknown-linux-gnu
            package: nodenexus-server
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            package: nodenexus-agent
          - os: ubuntu-22.04-arm
            target: aarch64-unknown-linux-gnu
            package: nodenexus-agent
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            package: nodenexus-agent
          - os: macos-13
            target: x86_64-apple-darwin
            package: nodenexus-agent
          - os: macos-14
            target: aarch64-apple-darwin
            package: nodenexus-agent
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}
      - name: Setup protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: backend/target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.target }}
      - name: Build backend
        env:
          APP_VERSION: ${{ github.ref_name }}
        run: cargo build --release -p ${{ matrix.package }} --target ${{ matrix.target }}
        working-directory: ./backend
      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package }}-${{ github.ref_name }}-${{ matrix.target }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}
          path: backend/target/${{ matrix.target }}/release/${{ matrix.package }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}

  release:
    needs: build_backend
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: List artifacts
        run: ls -R artifacts
      - name: Prepare release assets
        run: |
          mkdir release_assets
          for dir in artifacts/*; do
            if [ -d "$dir" ]; then
              asset_name=$(basename "$dir")
              file_in_dir=$(ls "$dir" | head -n 1)
              mv "$dir/$file_in_dir" "release_assets/$asset_name"
            fi
          done
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: release_assets/*