name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend
      - name: Build frontend
        run: npm run build
        working-directory: ./frontend
      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist

  build_backend:
    needs: build_frontend
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: server
            name: server-linux-amd64
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            bin: server
            name: server-linux-arm64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: agent
            name: agent-linux-amd64
          - os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            bin: agent
            name: agent-linux-arm64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: agent
            name: agent-windows-amd64.exe
          - os: macos-13
            target: x86_64-apple-darwin
            bin: agent
            name: agent-macos-amd64
          - os: macos-14
            target: aarch64-apple-darwin
            bin: agent
            name: agent-macos-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}
      - name: Setup protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo build
        uses: actions/cache@v3
        with:
          path: backend/target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.target }}
      - name: Build backend
        env:
          APP_VERSION: ${{ github.ref_name }}
        run: cargo build --release --bin ${{ matrix.bin }} --target ${{ matrix.target }}
        working-directory: ./backend
      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: backend/target/${{ matrix.target }}/release/${{ matrix.bin }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}

  release:
    needs: build_backend
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: List artifacts
        run: ls -R artifacts
      - name: Prepare release assets
        run: |
          mkdir release_assets
          mv artifacts/server-linux-amd64/server release_assets/server-linux-amd64
          mv artifacts/server-linux-arm64/server release_assets/server-linux-arm64
          mv artifacts/agent-linux-amd64/agent release_assets/agent-linux-amd64
          mv artifacts/agent-linux-arm64/agent release_assets/agent-linux-arm64
          mv artifacts/agent-windows-amd64.exe/agent.exe release_assets/agent-windows-amd64.exe
          mv artifacts/agent-macos-amd64/agent release_assets/agent-macos-amd64
          mv artifacts/agent-macos-arm64/agent release_assets/agent-macos-arm64
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: release_assets/*